sudo: required
services: 
    - docker

before_install:
    - docker build -t engkarimahmed/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true engkarimahmed/react-test npm run test

after_success:
    - docker build -t engkarimahmed/multi-client ./client
    - docker build -t engkarimahmed/multi-nginx ./nginx
    - docker build -t engkarimahmed/multi-server ./server
    - docker build -t engkarimahmed/multi-worker ./worker
    #Login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push engkarimahmed/multi-client
    - docker push engkarimahmed/multi-nginx
    - docker push engkarimahmed/multi-server
    - docker push engkarimahmed/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-044661511016"
    bucket_path: "docker"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    


    